language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ikaybraz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ikaybraz/docker-react npm run test 

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-431061218680"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"